version: 1.1.0
slug: filipinos_bot
name: Filipinos Bot
description: Filipinos Discord Bot
url: https://github.com/Ricfilipe/Filipinos-Bot-public
codenotary: notary@home-assistant.io
advanced: true
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true

options:
  discord_token: TOKEN
  github_token: TOKEN
  mongo_user: user
  mongo_pass: pass
  trakt_api_key: API_KEY
  watch_party_api: API_KEY
schema:
  mongo_user: str
  mongo_pass: str
  discord_token: str
  github_token: str
  trakt_api_key: str
  watch_party_api: str
