const { EmbedBuilder } = require('discord.js');
const Imgflip = require('imgflip')
require('dotenv').config();
const TOKEN_USER_IMGFLIP = process.env.TOKEN_USER_IMGFLIP;
const TOKEN_PASS_IMGFLIP = process.env.TOKEN_PASS_IMGFLIP;

const memeGenerator = new Imgflip.default({
    username: TOKEN_USER_IMGFLIP,
    password: TOKEN_PASS_IMGFLIP
})

module.exports= {
    json: {
        "name": "meme",
        "description": "Generates a meme",
        "options":[            {
            "name": "template-id",
            "description": "Template ID in imgflip",
            "type": 3,
            "required": true,
        },
        {
            "name": "text",
            "description": "Text that appears in the boxes (separated by ;)" +
                "",
            "type": 3,
            "required": true,
        },
        {
            "name": "font",
            "description": "Font used in text",
            "type": 3,
            "choices": [
                {
                    "name": "impact",
                    "value": "impact"
                },
                {
                    "name": "arial",
                    "value": "arial"
                }
            ],
            "required": false,
        }]
    },
    callback: async ({client, interaction, args, guild, member, user}) => {
        let templateId = interaction.options.getString("template-id")
        let captions = interaction.options.getString("text")
        let font = interaction.options.getString("font")
        if(font===undefined)
        {
            font = "impact"
        }

        captions = captions.split(";")
        if( !/^\d+$/.test(templateId)) // Checks if its only numbers
        {
            templateId = dictionary[templateId]
        }

        try {
            const embed = new EmbedBuilder()
            await interaction.deferReply();
            const response = await memeGenerator.meme(templateId, {captions: captions,font})

            embed.setImage(response)
                .setAuthor({ name: "Generated by Imgflip", iconURL: 'https://imgflip.com/imgflip_white_96.png', url: 'https://imgflip.com/' })
                .setFooter({text:"Requested by " + member.displayName, iconURL: user.avatarURL()})
            await interaction.editReply({embeds:[embed]});
        }
        catch (exception)
        {
            console.log("Something went wrong while generating the meme: " + exception.message);
            await interaction.editReply({content: "Something went wrong while generating the meme: " + exception.message});
        }
        return null
    }
}

// TODO: Move translation to DB
dictionary
    =
    {
        "Boss":"442694127"
    }